name: TS-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('backoffice/.env') || copy('backoffice/.env.example', 'backoffice/.env');"
      
    - name: Install Dependencies
      run: |
        cd backoffice
        composer install --no-ansi --no-interaction --no-progress --prefer-dist
      
    - name: Generate key
      run: |
        cd backoffice
        php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 backoffice/storage backoffice/bootstrap/cache

    - name: Test MySQL connection
      run: |
        mysql -h ${{ secrets.PRODUCTION_DB_HOST }} -P ${{ secrets.PRODUCTION_DB_PORT }} -u ${{ secrets.PRODUCTION_DB_USERNAME }} -p${{ secrets.PRODUCTION_DB_PASSWORD }} -e "SHOW DATABASES;"  

    - name: Wait for MySQL to be ready
      run: |
          for i in {1..60}; do
            mysqladmin ping -h ${{ secrets.PRODUCTION_DB_HOST }} --silent && break
            echo "Waiting for MySQL..."
            sleep 5
          done

    # - name: Execute migrations
    #   env:
    #     DB_CONNECTION: mysql
    #     DB_HOST: ${{ secrets.PRODUCTION_DB_HOST }}
    #     DB_PORT: ${{ secrets.PRODUCTION_DB_PORT }}
    #     DB_DATABASE: ${{ secrets.PRODUCTION_DB_DATABASE }}
    #     DB_USERNAME: ${{ secrets.PRODUCTION_DB_USERNAME }}
    #     DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
    #   run: |
    #     cd backoffice
    #     php artisan migrate

    - name: Deploy to Droplet
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DROPLET_IP: ${{ secrets.DROPLET_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/private_key
        chmod 600 /tmp/private_key
        ssh -i /tmp/private_key -o StrictHostKeyChecking=no root@$DROPLET_IP << 'EOF'
          cd /var/www/html/terrasol/backoffice
          git stash
          git pull origin main
          composer install --no-ansi --no-interaction --no-progress --prefer-dist
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          sudo systemctl restart nginx  # O el comando para reiniciar el servidor web que uses
        EOF
