name: TS-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('backoffice/.env') || copy('backoffice/.env.example', 'backoffice/.env');"
      
    - name: Install Dependencies
      run: |
        cd backoffice
        composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist
      
    - name: Generate key
      run: |
        cd backoffice
        php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 backoffice/storage backoffice/bootstrap/cache
      
    - name: Execute migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 174.138.108.156
        DB_PORT: 3306
        DB_DATABASE: terrasol_dev
        DB_USERNAME: TerraSol
        DB_PASSWORD: BDTS2k24.
      run: |
        cd backoffice
        php artisan migrate
      
    - name: Execute tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 174.138.108.156
        DB_PORT: 3306
        DB_DATABASE: terrasol_dev
        DB_USERNAME: TerraSol
        DB_PASSWORD: BDTS2k24.
      run: |
        cd backoffice
        vendor/bin/phpunit