name: TS-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v3
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql

    - name: Copy .env
      run: php -r "file_exists('backoffice/.env') || copy('backoffice/.env.example', 'backoffice/.env');"
      
    - name: Install Dependencies
      run: |
        cd backoffice
        composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist
      
    - name: Generate key
      run: |
        cd backoffice
        php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 775 backoffice/storage backoffice/bootstrap/cache
      
    - name: Execute migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        cd backoffice
        php artisan migrate --force
      
    - name: Execute tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: 3306
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        cd backoffice
        vendor/bin/phpunit
