name: TS-Build-Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql
          coverage: none

      - name: Install Composer Dependencies
        run: |
          cd backoffice
          composer install --no-ansi --no-interaction --no-progress --prefer-dist
      
      - name: Copy .env.example to .env
        run: |
            cd backoffice
            cp .env.example .env
  
      - name: Generate Application Key
        run: |
            cd backoffice
            php artisan key:generate

      - name: Set Directory Permissions
        run: |
          chmod -R 777 backoffice/storage backoffice/bootstrap/cache

      - name: Test MySQL Connection
        run: |
          mysql -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES;"

      - name: Wait for MySQL to be Ready
        run: |
          for i in {1..60}; do
            mysqladmin ping -h ${{ secrets.DB_HOST }} --silent && break
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          cd backoffice
          php artisan migrate --force

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            echo "Starting deployment..."
            cd /var/www/html/Terrasol-PT-Backoffice/
          ssh_private_key: ${{ secrets.DROPLET_SSH_KEY }} 

      - name: Pull Latest Changes
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            cd /var/www/html/Terrasol-PT-Backoffice/backoffice
            git pull origin main

      - name: Install Composer Dependencies (Droplet)
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            cd /var/www/html/Terrasol-PT-Backoffice/backoffice
            composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Run Migrations (Droplet)
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            cd /var/www/html/Terrasol-PT-Backoffice/backoffice
            php artisan migrate --force

      - name: Clear Cache
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            cd /var/www/html/Terrasol-PT-Backoffice/backoffice
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

      - name: Restart PHP-FPM
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            sudo service php8.3-fpm restart

      - name: Deployment Completed
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            echo "Deployment to Droplet complete!"